name: macOS x86_64
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Test install
      run: make
    - name: Check idempotency
      run: make
    - name: Test uninstall
      run: make clean
    - name: Check idempotency
      run: make clean
