name: Shellcheck
permissions: {}
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Run ShellCheck
      run: shellcheck -e SC2148,SC1091,SC2034 .zshrc
    - name: Run ShellCheck
      run: shellcheck -e SC2148,SC1091,SC2154,SC2016,SC2128,SC2296,SC2207 .zsh_prompt
